### ISSUE TITLE
Default controller present - tokenURI not being "found"

### ISSUE THREAD

**Issue by TheGreatAxios** [skalenetwork/blockscout#34]
**Describe the bug**
For Non-Fungible Token contracts, the graphic/tokenURI is not always being pulled up on the explorer and it shows the default controller.

**Proof/Reproduction**
(does not show up) tokenId 966 - https://fussy-smoggy-megrez.explorer.mainnet.skalenodes.com/token/0xcfb23c3f910d59311fcccbeeee8c28c0156582c7/instance/966/token-transfers

(shows up )tokenId 698 - https://fussy-smoggy-megrez.explorer.mainnet.skalenodes.com/token/0xcfb23c3f910d59311fcccbeeee8c28c0156582c7/instance/698/token-transfers

**Expected behavior**
Both should show the same graphic since they are the same graphic

**Additional context**

**Comment by payvint** [comment]
Not showing: https://fussy-smoggy-megrez.explorer.mainnet.skalenodes.com/token/0xb8538ae6f6eb0615ab924bff646c4e7173bd1470/instance/30000000011/token-transfers

Showing: https://fussy-smoggy-megrez.explorer.mainnet.skalenodes.com/token/0xb8538ae6f6eb0615ab924bff646c4e7173bd1470/instance/20000000025/token-transfers
