### ISSUE TITLE
Fix too big Etherbase balance on Verified contracts page

### ISSUE THREAD

**Issue by yavrsky** [skalenetwork/blockscout#52]
### Description

Balance of Etherbase break UI because it's too big, consider using exponential notation for fixing this.
https://round-hasty-alsafi.explorer.mainnet.skalenodes.com/verified-contracts
![image](https://github.com/skalenetwork/blockscout/assets/39807321/701a2bc8-083d-40b7-8ed9-4f03f36420a7)

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Geth

### Backend version

v2.0.0

### Frontend version

v1.28.1

### Elixir & Erlang/OTP versions

Elixir 1.14.5

**Comment by yatsunastya** [comment]
Checked :white_check_mark: 
Version: `2.1.0-beta.2`

![Image](https://github.com/user-attachments/assets/7a9de9cf-8b25-47cb-9814-c5e9681cd007)
