### ISSUE TITLE
Contracts rendered as plain account

### ISSUE THREAD

**Issue by cstrangedk** [skalenetwork/blockscout#9]
Some contracts are not recognized as such in the explorer.  Might this be an indexing delay or is there some other problem?  I can get the code for this particular contract address and I can interact with it over web3 APIs however it is rendered as a plain account in the explorer.  http://glamorous-syrma.explorer.dappnet.skalenodes.com/address/0x33D732Aa32b00B3817D43AA0AAbaF2c735d50E7F/transactions

**Comment by DmytroNazarenko** [comment]
This issue caused by inaccurate migration dappnet blockexplorers to a new instance
